parallel/__init__.py,sha256=K05U5RWR9AsisAInaDskWEtmcRtPFlXRYAzGdM_g6F0,11062
parallel/errors.py,sha256=Rd19roFbQA3QqIP9ALdCMlXvgJBguipuqDQrWj4sMhA,299
parallel/exceptions.py,sha256=ON8MTq765dtP5qe2Xq8GDXvbTQpBNJ5PW5q40b-WwZ4,232
parallel/models.py,sha256=10Z68_XqdVb5dUNrxpo5gAPvIXUBJOAm7kYx0wjnEuw,5772
parallel/process.py,sha256=f6w4eLckiQ_d8zw8CHpDZJ2U-e5wWtoX7M86B7KgLi4,63
parallel/utils.py,sha256=WDI8c7qPB4USIqSEZxuSr2haLwoUCo6tX7tXtbSf4Dk,474
python_parallel-0.9.0.dist-info/LICENSE,sha256=zepAmBMeFxeOOfSnEt21kjbkukEOai9aXJ0y3dZTSg0,1102
python_parallel-0.9.0.dist-info/WHEEL,sha256=KvY1g7zIOl4mQEMkderYQrWQRhoTqMOhqr9g8hbxY54,85
python_parallel-0.9.0.dist-info/METADATA,sha256=fymleq0OOzkd6WlKH6usVDQgIJxDCcdaaInuKQ2olk8,471
python_parallel-0.9.0.dist-info/RECORD,,
